[project]
name = "jobpulse"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Amir Yaghobi", email = "amiram1544@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
jobpulse = "jobpulse:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
